### ISSUE TITLE
0.7.0 Release todo

### ISSUE THREAD

**Issue by vict0rsch** [vict0rsch/PaperMemory#191]
* [x] Update sources (MDPI & OUP) in the docs & readme
* [x] Use UnpayWall API to match preprints https://unpaywall.org/products/api
	* [x] Update docs accordingly
	* [x] Is there another use-case for UW without duplicating their work in their extension?
